import type { MetadataRoute } from 'next'

// Base URL shared with sitemap
const BASE_URL = 'https://commitlabs.com'

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: '*',
        allow: '/',
      },
    ],
    // Reference the same sitemap generated by src/app/sitemap.ts
    sitemap: `${BASE_URL}/sitemap.xml`,
  }
}
